# Generated by Django 3.1.5 on 2021-05-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='courseCode',
            field=models.CharField(default='None', max_length=100, primary_key=True, serialize=False),
        ),
    ]
