# Generated by Django 3.1.5 on 2021-05-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210501_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursematerials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('type', models.CharField(max_length=300)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Files1',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='courseCode',
        ),
    ]
